### ISSUE TITLE
does not work with rails 4.1beta1

### ISSUE THREAD

**Issue by alec-c4** [RolifyCommunity/rolify#209]
Hi,
there are problem with rails 4.1beta1

```
2.0.0p247 :001 > User.first.add_role :admin
  User Load (1.3ms)  SELECT  "users".* FROM "users"   ORDER BY "users"."id" ASC LIMIT 1
NoMethodError: undefined method `find_or_create_by_name_and_resource_type_and_resource_id' for #<Class:0x007ff5644f6120>
    from /Users/alec/.rvm/gems/ruby-2.0.0-p247@morton_social/gems/activerecord-4.1.0.beta1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
    from /Users/alec/.rvm/gems/ruby-2.0.0-p247@morton_social/gems/rolify-3.2.0/lib/rolify/adapters/active_record/role_adapter.rb:12:in `find_or_create_by'
    from /Users/alec/.rvm/gems/ruby-2.0.0-p247@morton_social/gems/rolify-3.2.0/lib/rolify/role.rb:12:in `add_role'
```
