### PR TITLE
Fix deprecation warnings in Ruby 2.7

### PR DESCRIPTION
**Pull request by nburt**
I was getting `undefined method `new' for BigDecimal:Class` errors after upgrading to 2.7 which is why I pinned the bigdecimal versions for older versions of activesupport

I'm new to testing across multiple gemfiles + ruby versions and welcome any feedback on whether or not this is the right way to do it

### CODE REVIEW

**Comment by nburt** [comment]
@EppO For bigdecimal this is the error I was getting: https://github.com/ruby/bigdecimal/issues/127

**Comment by thomas-mcdonald** [comment]
Thank you @nburt! PR looks great. Hopefully we can get rid of the bigdecimal overrides once we drop support for these old versions after this release.
