### ISSUE TITLE
dynamic shortcuts with resources argument error - undefined method `id' for :any:Symbol

### ISSUE THREAD

**Issue by francescob** [RolifyCommunity/rolify#469]
This syntax 

`user.is_data_manager_of?(:any)`

used to work in rolify 4.0.0

now I've upgraded to rolify 5.1.0

I got the error 

`NoMethodError: undefined method `id' for :any:Symbol`

while `user.has_role?(:data_manager, :any)` works correctly

Is this intended behavior?
