### ISSUE TITLE
NoMethodError: undefined method `find_each' for #<Mongoid::Criteria:0x00000006140270>

### ISSUE THREAD

**Issue by vovanmozg** [RolifyCommunity/rolify#350]
it raised error after update to 4.1.0.

Trace:
```
NoMethodError: undefined method `find_each' for #<Mongoid::Criteria:0x00000006140270>
/home/www/.rvm/gems/ruby-2.2.0@rails420/gems/mongoid-4.0.2/lib/mongoid/criteria.rb:523:in `method_missing'
/home/www/.rvm/gems/ruby-2.2.0@rails420/gems/rolify-4.1.0/lib/rolify/dynamic.rb:14:in `load_dynamic_methods'
/home/www/.rvm/gems/ruby-2.2.0@rails420/gems/rolify-4.1.0/lib/rolify.rb:33:in `rolify'
/home/www/rails_projects/cerebrum/app/models/user.rb:5:in `<class:User>'
...
```
when i call:
```
user = User.find_by(email: 'email@email.ru')
```
Model User:
```
class User
  include Mongoid::Document
  rolify
  include Mongoid::Timestamps
```

When i rollback to 4.0.0 all working fine.

**Comment by wldcordeiro** [comment]
I'll have to inspect this further, thanks for reporting. If you can get any additional info such as stack traces, method calls, etc it'd be much appreciated..

**Comment by wldcordeiro** [comment]
From researching, `.find_each` isn't supported in Mongoid, but we have an if block that checks for the existence of Mongoid and then doesn't define that method for it, odd.

**Comment by wldcordeiro** [comment]
I've tried changing something in the system, could you try installing the most recent commit (rather than the published gem) and testing?

**Comment by vovanmozg** [comment]
```
2.2.0 :001 > ENV['ADAPTER']
 => nil 
```

**Comment by vovanmozg** [comment]
Last commit helped me. Thank you!

**Comment by wldcordeiro** [comment]
Cool, I'll be pushing a 4.1.1 release pretty soon with that fix so you'll be able to use the gem.

**Comment by wldcordeiro** [comment]
@vovanmozg FYI 4.1.1 is now out on rubygems.
