### ISSUE TITLE
Ruby 2.2 Incompatibility

### ISSUE THREAD

**Issue by Hamdan85** [RolifyCommunity/rolify#332]
I think the gem is not compatible with ruby 2.2. Is it right?

There are something happening with associations. When I use rake db:seed i got several errors related to objets that uses roleify gem, but only in Ruby 2.2

Its something about the way the gem uses the associations.

Could you check?

Thanks in advance.

**Comment by wldcordeiro** [comment]
It works with Ruby 2.2 there's only some warnings about the associations but that's a Rails warning not Ruby.

**Comment by Hamdan85** [comment]
For me there was more than warnings. I got real errors that prevented migrations and server start for example.

**Comment by wldcordeiro** [comment]
I'm using Rolify 4.0.0 on Ruby 2.2.2 with Rails 4.2.0 and have only warnings in a production site. Can you post your logs and any other relevant snippets?

**Comment by Hamdan85** [comment]
Ill try to do this at home tonight.

2015-04-22 14:17 GMT-03:00 Wellington Cordeiro <notifications@github.com>:

**Comment by jamescgibson** [comment]
I can confirm that Rolify 4.0.0, which works on a production app with Ruby 2.1.4, breaks with both Ruby 2.2.1 and Ruby 2.2.2. The error that I'm seeing ultimately traces to a call to model.add_role :role_name, but manifests as "NoMethodError: undefined method `name` for nil:NilClass`.

**Comment by wldcordeiro** [comment]
What Rails version are you guys using?

**Comment by wldcordeiro** [comment]
These are the warnings I get.
```
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations.rb:1694: warning: already initialized constant User::HABTM_Roles
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/associations.rb:1694: warning: previous definition of HABTM_Roles was here
```
Can you guys provide some logs and information on your installations?

**Comment by Hamdan85** [comment]
Thats the same error that I'm facing by the way. This 'name' thing.

2015-04-24 14:41 GMT-03:00 Wellington Cordeiro <notifications@github.com>:

**Comment by andradei** [comment]
Would you guys list the Rails version and the error/warning logs + anything else that might help us figure out the issue?

**Comment by Hamdan85** [comment]
I think mine version is 4.1.1

2015-04-24 18:39 GMT-03:00 Isaac Andrade <notifications@github.com>:

**Comment by jamescgibson** [comment]
Same, Rails 4.1.1. Here's a log from running `rake db:seed`; line 7 is just `user.add_role :admin`. 

```
NoMethodError: undefined method `name' for nil:NilClass
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:79:in `cached_counter_attribute_name'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:75:in `has_cached_counter?'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:83:in `update_counter'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_through_association.rb:65:in `insert_record'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:522:in `block (2 levels) in concat_records'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:521:in `block in concat_records'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:519:in `each'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:519:in `concat_records'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_through_association.rb:42:in `concat_records'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:153:in `block in concat'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:167:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:153:in `concat'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/has_many_through_association.rb:36:in `concat'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:507:in `replace_records'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:362:in `block in replace'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:167:in `transaction'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:362:in `replace'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:61:in `ids_writer'
/home/james/.rvm/gems/ruby-2.2.2/gems/activerecord-4.1.1/lib/active_record/associations/builder/collection_association.rb:76:in `role_ids='
/home/james/.rvm/gems/ruby-2.2.2/gems/rolify-4.0.0/lib/rolify/adapters/active_record/role_adapter.rb:16:in `add'
/home/james/.rvm/gems/ruby-2.2.2/gems/rolify-4.0.0/lib/rolify/role.rb:19:in `add_role'
/home/james/dev/teetimer/db/seeds.rb:7:in `<top (required)>'
```

**Comment by jhixson** [comment]
I was having a similar issue, but then realized I didn't have `resourcify` in my associated model. Everything working for me as of now (Ruby 2.2.0, Rails 4.2.1)

**Comment by seoyoochan** [comment]
I have the same issue (Ruby 2.2.2, Rails 4.2.3)
```
seos-MacBook:seoyoochan seoyoochan$ rake db:seed
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'user_id' for User::HABTM_Roles.
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:35:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:169:in `initialize_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:248:in `block in build_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/core.rb:283:in `initialize'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/inheritance.rb:61:in `new'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/inheritance.rb:61:in `new'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/reflection.rb:131:in `build_association'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:247:in `build_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:146:in `build'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:95:in `build_through_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:48:in `block in concat_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:47:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:47:in `concat_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:166:in `concat'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:546:in `replace_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:369:in `replace'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:67:in `ids_writer'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/builder/collection_association.rb:76:in `role_ids='
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/rolify-4.0.0/lib/rolify/adapters/active_record/role_adapter.rb:16:in `add'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/rolify-4.0.0/lib/rolify/role.rb:19:in `add_role'
/Users/seoyoochan/dev/seoyoochan/db/seeds.rb:11:in `<top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `eval'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `user_id=' for #<User::HABTM_Roles users_id: nil, role_id: nil>
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:54:in `public_send'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:35:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:169:in `initialize_attributes'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:248:in `block in build_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/core.rb:283:in `initialize'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/inheritance.rb:61:in `new'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/inheritance.rb:61:in `new'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/reflection.rb:131:in `build_association'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/association.rb:247:in `build_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:146:in `build'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:95:in `build_through_record'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:48:in `block in concat_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:47:in `each'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:47:in `concat_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:166:in `concat'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/has_many_through_association.rb:38:in `concat'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:546:in `replace_records'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:369:in `replace'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:67:in `ids_writer'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/associations/builder/collection_association.rb:76:in `role_ids='
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/rolify-4.0.0/lib/rolify/adapters/active_record/role_adapter.rb:16:in `add'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/rolify-4.0.0/lib/rolify/role.rb:19:in `add_role'
/Users/seoyoochan/dev/seoyoochan/db/seeds.rb:11:in `<top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `eval'
/Users/seoyoochan/.rvm/gems/ruby-2.2.2@api/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

this happened when using `user.add_role :admin`

**Comment by boykoc** [comment]
Have you checked issue #315? It seems to mention the same thing and the fix. `rolify `adds the association.
